#pragma once

#define APPROVAL_TESTS_QT_VERSION_MAJOR 0
#define APPROVAL_TESTS_QT_VERSION_MINOR 0
#define APPROVAL_TESTS_QT_VERSION_PATCH 2
#define APPROVAL_TESTS_QT_VERSION_STR "0.0.2"

#define APPROVAL_TESTS_QT_VERSION                                                        \
    (APPROVAL_TESTS_QT_VERSION_MAJOR * 10000 + APPROVAL_TESTS_QT_VERSION_MINOR * 100 +   \
     APPROVAL_TESTS_QT_VERSION_PATCH)
